# Generated by Django 2.0.1 on 2018-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=80)),
                ('alias_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(to='carlo.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=80)),
                ('alias_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='groupmembermap',
            name='member',
            field=models.ManyToManyField(to='carlo.Member'),
        ),
    ]
